 export const jobsData = [
    {
      title: "Associate Sales Consultant (Delhi)",
      company: "Paisabazaar",
      location: "Delhi",
      salary: "₹ 2,25,000 - 2,65,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Job",
    },
    {
      title: "Camera Person",
      company: "PlanetSpark",
      location: "Gurgaon",
      salary: "₹ 5,00,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Internship",
    },
    {
      title: "Revenue Growth Associate",
      company: "PlanetSpark",
      location: "Gurgaon",
      salary: "₹ 6,50,000 - 7,50,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Job",
    },
    {
      title: "Corporate Sales Executive",
      company: "PlanetSpark",
      location: "Gurgaon, Lucknow",
      salary: "₹ 6,50,000 - 7,50,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Part-Time",
    },
    {
      title: "Freelance Designer",
      company: "Freelance Agency",
      location: "Remote",
      salary: "₹ 1,00,000 - 2,00,000 /project",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Freelancing",
    },
    {
      title: "Customer Support (Work From Home)",
      company: "TechCorp",
      location: "Remote",
      salary: "₹ 3,00,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Work From Home",
    },
    {
      title: "Marketing Intern",
      company: "XYZ Solutions",
      location: "Mumbai",
      salary: "₹ 20,000 /month",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Internship",
    },
    {
      title: "Graphic Designer",
      company: "DesignHub",
      location: "Bangalore",
      salary: "₹ 4,50,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Job",
    },
    {
      title: "Software Engineer",
      company: "TechSolutions",
      location: "Pune",
      salary: "₹ 8,00,000 - 10,00,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Job",
    },
    {
      title: "Data Scientist Intern",
      company: "DataCorp",
      location: "Remote",
      salary: "₹ 30,000 /month",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Internship",
    },
    {
      title: "Sales Manager",
      company: "RetailCo",
      location: "Delhi",
      salary: "₹ 12,00,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Job",
    },
    {
      title: "Part-Time Content Writer",
      company: "WriteNow",
      location: "Remote",
      salary: "₹ 25,000 /month",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Part-Time",
    },
    {
      title: "Freelance Web Developer",
      company: "WebDev Agency",
      location: "Remote",
      salary: "₹ 2,00,000 - 3,00,000 /project",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Freelancing",
    },
    {
      title: "UI/UX Designer",
      company: "DesignCo",
      location: "Bangalore",
      salary: "₹ 7,50,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Job",
    },
    {
      title: "Social Media Intern",
      company: "MediaCorp",
      location: "Delhi",
      salary: "₹ 15,000 /month",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Internship",
    },
    {
      title: "Customer Success Manager",
      company: "TechServe",
      location: "Noida",
      salary: "₹ 9,00,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Job",
    },
    {
      title: "HR Manager (Part-Time)",
      company: "HR Solutions",
      location: "Remote",
      salary: "₹ 6,00,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Part-Time",
    },
    {
      title: "Freelance Content Writer",
      company: "ContentNow",
      location: "Remote",
      salary: "₹ 1,00,000 - 1,50,000 /project",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Freelancing",
    },
    {
      title: "Work From Home Virtual Assistant",
      company: "RemoteServices",
      location: "Remote",
      salary: "₹ 3,50,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Work From Home",
    },
    {
      title: "Junior Developer (Internship)",
      company: "TechLabs",
      location: "Chennai",
      salary: "₹ 10,000 /month",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Internship",
    },
    {
      title: "SEO Specialist",
      company: "DigitalWorld",
      location: "Bangalore",
      salary: "₹ 4,00,000 /year",
      activelyHiring: true,
      logo: "https://via.placeholder.com/50",
      link: "#",
      type: "Job",
    },
  ];
  